comercial/urls.py
from django.urls import path

from . import views as v

app_name = 'comercial'

urlpatterns = [
    #path('', v.pedidos_list, name = 'pedidos_list'),
    path('detail/<ped_id>', v.pedido_detail, name = 'pedido_detail'),
    path('read/<int:pk>', v.Pedido_read.as_view(), name = 'pedido_read'),
    path('update/<int:pk>', v.Pedido_update.as_view(), name='pedido_update'),
    path('delete/<int:pk>', v.Pedido_delete.as_view(), name='pedido_delete'),
    path('filter/', v.Pedido_filter.as_view(), name='pedido_filter'),
    path('create/', v.Pedido_create.as_view(), name='pedido_create'),
    path('new/search_table', v.pedidos_prod_search_table, name='pedidos_prod_search_table'),
    path('pedidos/', v.pedidos, name='pedidos'),
    path('pedido_add_item/', v.Pedido_add_item.as_view(), name='pedido_add_item'),
    
    #Pedido
    path('pedido/list/', v.pedidos_list, name = 'pedidos_list'),
    path('pedido/new/', v.pedido_new, name='pedido_new'),
    path('pedido_detail/<pedido_id>', v.pedido_detail, name = 'pedido_detail'),
    path('pedido_full/search/', v.pedidos_prod_search, name='pedidos_prod_search'),
    path('pedido_full/prod_selected/', v.pedido_item_add, name='pedido_item_add'),
    path('pedido_full/item_delete/', v.pedido_item_delete, name='pedido_item_delete'),
    path('pedido_full/create/', v.pedido_new, name='pedido_new'),
    path('pedido_full/entrega_add/', v.pedido_entrega_add, name='pedido_entrega_add'),
    path('pedido_full/lote/', v.pedido_lote, name='pedido_lote'),
    #path('pedido_full/testaJson/', v.pedido_testaJson, name='pedido_testaJson'),

    #Orçamento
    path('orcamento/new/', v.orcamento_new, name='orcamento_new'),
    path('orcamento/list/', v.orcamento_list, name='orcamento_list'),
    path('orcamento/detail/<orcamento_id>', v.orcamento_detail, name = 'orcamento_detail'),
    path('orcamento/prod_search', v.orcamento_prod_search, name = 'orcamento_prod_search'),
    path('orcamento/item_add', v.orcamento_item_add, name = 'orcamento_item_add'),
    path('orcamento/item_delete', v.orcamento_item_delete, name = 'orcamento_item_delete'),
    path('orcamento/delete/', v.orcamento_delete, name = 'orcamento_delete'),
    path('orcamento/pedido_add', v.orcamento_pedido_add, name = 'orcamento_pedido_add'),
    
    #Entega
    path('entrega/new/', v.entrega_new, name='entrega_new'),
    path('entrega/list/', v.entrega_list, name='entrega_list'),
    path('entrega/detail/<entrega_id>', v.entrega_detail, name = 'entrega_detail'),
    path('entrega/prod_search', v.entrega_prod_search, name = 'entrega_prod_search'),
    path('entrega/item_add', v.entrega_item_add, name = 'entrega_item_add'),
    path('entrega/item_delete', v.entrega_item_delete, name = 'entrega_item_delete'),
    path('entrega/delete/', v.entrega_delete, name = 'entrega_delete'),
    path('entrega/pre_nota_add', v.pre_nota_add, name = 'pre_nota_add'),
    path('entrega/pre_nota_retorno', v.pre_nota_retorno, name = 'pre_nota_retorno'),
    path('entrega/pre_nota_estorno', v.pre_nota_estorno, name = 'pre_nota_estorno'),
    path('entrega/label', v.label, name = 'label'),
]

core/urls.py
from django.urls import path
from . import views as v

app_name = 'core'

urlpatterns = [
    path('', v.index, name='index'),
]

entradas/urls.py
from django.urls import path

from . import views as v

app_name = 'entradas'

urlpatterns = [
    #Notas de entrada
    path('nf/list', v.nf_entrada_list, name = 'nf_entrada_list'),
    path('nf/new', v.nf_entrada_new, name = 'nf_entrada_new'),
    path('nf/filter', v.nf_entrada_filter, name = 'nf_entrada_filter'),
    path('nf/read/<int:pk>', v.nf_entrada_read, name = 'nf_entrada_read'),
    path('nf/<int:pk>', v.nf_entrada_detail, name = 'nf_entrada_detail'),
    path('nf/prod_search', v.nf_entrada_prod_search, name = 'nf_entrada_prod_search'),
    path('nf/item_add', v.nf_entrada_item_add, name = 'nf_entrada_item_add'),
    path('nf/item_delete', v.nf_entrada_item_delete, name = 'nf_entrada_item_delete'),
    path('nf/delete/', v.nf_entrada_delete, name = 'nf_entrada_delete'),
    path('nf/parcelas/create', v.nf_entrada_parcelas_create, name = 'nf_entrada_parcelas_create'),
    path('nf/parcelas/delete', v.nf_entrada_parcelas_delete, name = 'nf_entrada_parcelas_delete'),
    path('nome-autocomplete/', v.NomeAutocomplete.as_view(), name='nome-autocomplete'), 
    path('transportadora-autocomplete/', v.TransportadoraAutocomplete.as_view(), name='transportadora-autocomplete'), 

    #Ordem de compra
    path('oc/list', v.oc_list, name = 'oc_list'),
    path('oc/new', v.oc_new, name = 'oc_new'),
    path('oc/<int:pk>', v.oc_detail, name = 'oc_detail'),
    path('oc/prod_search', v.oc_prod_search, name = 'oc_prod_search'),
    path('oc/item_add', v.oc_item_add, name = 'oc_item_add'),
    path('oc/item_delete', v.oc_item_delete, name = 'oc_item_delete'),
    path('oc/delete/', v.oc_delete, name = 'oc_delete'),
    path('oc/print', v.oc_print, name = 'oc_print'),
    path('oc/email', v.oc_email, name = 'oc_email'),
    path('oc/send_email', v.send_email, name = 'send_email'),
    path('oc/oc_pdf', v.oc_pdf, name = 'oc_pdf'),
    path('oc/reports', v.OC_reports.as_view()),

   
    #Solicitação de materiais
    path('sm/list', v.sm_list, name = 'sm_list'),
    path('sm/new', v.sm_new, name = 'sm_new'),
    path('sm/<int:pk>', v.sm_detail, name = 'sm_detail'),

]

feito/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'Sistema Gerencial DEFER'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('core.urls')),
    path('prod/', include('prod.urls')),
    path('cyber/', include('cyber_sinc.urls')),
    path('com/', include('comercial.urls')),
    path('cad/', include('cadastro.urls')),
    path('pop/', include('modalform.urls')),
    path('fin/', include('financeiro.urls')),
    path('ent/', include('entradas.urls')),
    path('est/', include('estoque.urls')),
    path('pr/', include('producao.urls')),
    path('rel/', include('reports.urls')),
    path('caixa/', include('caixa.urls')),
    
]

financeiro/urls.py
from django.urls import path

from . import views as v

app_name = 'financeiro'

urlpatterns = [
    path('cp/list', v.cp_list, name = 'cp_list'),
    path('cp/filter', v.cp_filter, name = 'cp_filter'),
    path('cp/lote', v.cp_lote, name = 'cp_lote'),
    path('cp/new', v.cp_new, name = 'cp_new'),
    path('cp/detail/<int:pk>', v.cp_detail, name = 'cp_detail'),
    path('parc-autocomplete/', v.ParcAutocomplete.as_view(), name='parc-autocomplete'),
    path('entrada-autocomplete/', v.EntradaAutocomplete.as_view(), name='entrada-autocomplete'),
    
    #CR
    path('cr/list', v.cr_list, name = 'cr_list'),
    path('cr/filter', v.cr_filter, name = 'cr_filter'),
    path('cr/lote', v.cr_lote, name = 'cr_lote'),
    path('cr/new', v.cr_new, name = 'cr_new'),
    path('cr/detail/<int:pk>', v.cr_detail, name = 'cr_detail'),
    path('parc-autocomplete/', v.ParcAutocomplete.as_view(), name='parc-autocomplete'),
    path('entrega-autocomplete/', v.EntregaAutocomplete.as_view(), name='entrega-autocomplete'),


]

producao/urls.py
from django.urls import path

from . import views as v

app_name = 'producao'

urlpatterns = [
    path('op/list', v.op_list, name = 'op_list'),
    path('op/new', v.op_new, name = 'op_new'),
    path('prod/auto', v.ProdutoAutocomplete.as_view(), name = 'produto-autocomplete'),
    path('op/<int:pk>', v.op_detail, name = 'op_detail'),
    path('op/detail/delitem', v.op_delitem, name = 'op_delitem'),
    path('op/comp-fis/add', v.op_comp_fis_add, name = 'op_comp_fis_add'),
    path('pdf', v.pdf, name = 'pdf'),
    path('rpt_op', v.rpt_op, name = 'rpt_op'),
    path('op/prod_save', v.prod_save, name='prod_save'),
    #MRP
    path('mrp_list', v.mrp_list, name = 'mrp_list'),
    path('mrp_filter', v.mrp_filter, name = 'mrp_filter'),
]

producao/forms.py
from email.policy import default
from random import choices
from django import forms

from .models import *
from crispy_forms.layout import Button, Hidden, Layout, Field, Fieldset, Div, HTML, ButtonHolder, Submit
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column
from django.forms.formsets import BaseFormSet
from decimal import Decimal
from django.forms import Form, ModelForm, DateField, widgets
from core.services import *
from bootstrap_modal_forms.forms import BSModalModelForm, BSModalForm
from bootstrap_modal_forms.mixins import PopRequestMixin, CreateUpdateAjaxMixin
from dal import autocomplete
from financeiro.models import Conta_pagar
import djhacker
from datetime import datetime

class OP_detail_form(forms.ModelForm):

    qtd_producao = forms.CharField(max_length=15, label='Qtd producao', required=False, widget=forms.TextInput(attrs={'size': '7'}))
    qtd_perdida = forms.CharField(max_length=15, label='Qtd perda', required=False, widget=forms.TextInput(attrs={'size': '7'}))
    data_producao = forms.DateField(label='Data producao', required=False, initial=datetime.now(), widget=forms.DateInput(format=('%d/%m/%Y')))
    encerrar = forms.BooleanField(label='Encerrar OP?', initial=False, required=False)

    class Meta:
        model = OP
        fields = '__all__' 
        widgets = {
            'produto': autocomplete.ModelSelect2(
                url='producao:produto-autocomplete',
                attrs={'data-minimum-input-length': 3,
                },
                ),
        }

class OP_comp_fis_BaseFormSet(BaseFormSet):
    def clean(self): 
        if any(self.errors):
           # Don't bother validating the formset unless each form is valid on its own
           print(self.errors)
           return

        for form in self.forms:
            #print(form)
            try:
                pass
            except:
                print('erro')

class OP_comp_fis_formset(forms.Form):
    
    item_id = forms.CharField(max_length=30, label='Código', required=False, disabled=False, widget=forms.TextInput(attrs={'size': '1'}))
    source = forms.CharField(max_length=30, label='Código', required=False, disabled=False, widget=forms.TextInput(attrs={'size': '1'}))
    cod = forms.CharField(max_length=30, label='Código', required=False, disabled=True, widget=forms.TextInput(attrs={'size': '8'}))
    desc = forms.CharField(max_length=60, label='Descrição', required=False, disabled=False, widget=forms.TextInput(attrs={'size': '60'}))
    unid = forms.CharField(max_length=6, label='Unidade', required=False, disabled=True, widget=forms.TextInput(attrs={'size': '7'}))
    qtd_programada = forms.CharField(max_length=15, label='Quantidade', required=False, widget=forms.TextInput(attrs={'size': '7'}))
    custo_unit = forms.CharField(max_length=15, label='Custo Unitário', required=False, widget=forms.TextInput(attrs={'size': '7'}))
    custo_tot = forms.CharField(max_length=15, label='Custo Total', required=False, disabled=True, widget=forms.TextInput(attrs={'size': '7'}))



class OP_serv_int_BaseFormSet(BaseFormSet):
    def clean(self): 
        if any(self.errors):
           # Don't bother validating the formset unless each form is valid on its own
           print(self.errors)
           return

        for form in self.forms:
            #print(form)
            try:
                pass
            except:
                print('erro')

SOURCE = (
    ('SI', 'SI'),
    ('SE', 'SE'),
    ('CF', 'CF'),
)

class OP_serv_int_formset(forms.Form):

    oper = Parceiro.objects.filter(tipo__sigla = 'OP')
    
    item_id = forms.CharField(max_length=30, label='Código', required=False, disabled=False, widget=forms.TextInput(attrs={'size': '1'}))
    source = forms.CharField(max_length=30, label='Código', required=False, disabled=False, widget=forms.TextInput(attrs={'size': '1'}))
    nivel = forms.CharField(max_length=30, label='Nível', required=False, disabled=False, widget=forms.TextInput(attrs={'size': '1'}))
    cod = forms.CharField(max_length=30, label='Código', required=False, disabled=True, widget=forms.TextInput(attrs={'size': '8'}))
    desc = forms.CharField(max_length=60, label='Descrição', required=False, disabled=False, widget=forms.TextInput(attrs={'size': '60'}))
    unid = forms.CharField(max_length=6, label='Unidade', required=False, disabled=True, widget=forms.TextInput(attrs={'size': '7'}))
    tempo_estimado = forms.CharField(max_length=15, label='Quantidade', required=False, widget=forms.TextInput(attrs={'size': '7'}))
    custo_unit = forms.CharField(max_length=15, label='Custo Unitário', required=False, widget=forms.TextInput(attrs={'size': '7'}))
    custo_tot = forms.CharField(max_length=15, label='Custo Total', required=False, disabled=True, widget=forms.TextInput(attrs={'size': '7'}))
    operador = forms.ModelChoiceField(queryset=oper)
    source = forms.ChoiceField(choices=SOURCE, label='Tipo', required=False, disabled=False)

producao/templates/producao/mrp_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container-fluid">

  <div class="form-row">
    <div class="form-group col-md-4 mb-0">
      <h4><strong>MRP - Necessidades de material</strong></h4>
    </div>
    <div class="form-group col-md-4 mb-0">
      <form method="get" id="acao_lote"></form>
      {{ lote.opcoes|as_crispy_field }}
    </div>
    <div class="form-group col-md-4 mb-0">
      <button type="button" class="btn btn-primary" onclick="lote(this);">Executar</button>
      <button id="filter" class="filter-pedido btn btn-primary" type="button" name="button" data-form-url="{% url 'producao:mrp_filter' %}">
        <span class="fa fa-filter mr-2"></span>Filtrar
      </button>
    </div>
  </form>
</div>

  <p> </p>   
  {% include "producao/mrp_list_table.html" %}     


</div>

<div class="modal fade" id="filtro" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg " role="document">
    <div class="modal-content">
      
      <div class="modal-header">
        <h5 class="modal-title" id="send_mail">Filtro do MRP</h5>       
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>

      <div class="modal-body">
        <div class="container" id="filtro">
          <form method="get" id="filtro-form">
            {{ lista.form|crispy }}
            <button type="submit" class="btn btn-primary" >Filtrar</button>
          </form>
        </div>
      </div>

    </div>
  </div>
</div>

{% endblock content %}

{% block extrascripts %}
<script type="text/javascript">

  $(".detail").click(function(){
    var url = $(this).attr('data-form-url');
    location.href = url  
  });

  $(".read").click(function(){
    var url = $(this).attr('data-form-url');
    $(this).modalForm({formURL: $(this).data("form-url")}); 
  });

  $("#filter").click(function () {
    $("#filtro").modal('toggle')
  });


  function toggle(source) {
    var checkboxes = document.querySelectorAll('input[type="checkbox"]');
    for (var i = 0; i < checkboxes.length; i++) {
        if (checkboxes[i] != source)
            checkboxes[i].checked = source.checked;
    }
  }

  function lote(source) {
    let checkboxes = document.querySelectorAll('input[name="chk"]:checked');
    let lote_opt = document.getElementById("id_opcoes").value
    let values = [];
    checkboxes.forEach((checkbox) => {
        values.push(checkbox.value);
    });
    console.log(values);
    console.log(lote_opt);
    send_lote(values, lote_opt)
  } 

  function send_lote(chkeds, opt) {

    let data = new FormData();
    data.append('chkeds', chkeds);;
    data.append('opt', opt);
    // add form input from hidden input elsewhere on the page
    data.append('csrfmiddlewaretoken', '{{ csrf_token }}')

    console.log(JSON.stringify(data))

    fetch("{% url 'financeiro:cp_lote' %}", {
        method: 'POST',
        body: data,
        credentials: 'same-origin',
        headers: {"X-CSRFToken": '{{ csrf_token }}'}
    }).then((response) => {
        console.log(response)
    }).then((res) => {
        if (res.status === 201) {
            console.log("Post successfully created!")
        }
    }).catch((error) => {
        console.log(error)
    })
  }

</script>
{% endblock extrascripts %}

producao/templates/producao/op_comp_fis_table.html
{{ formset.management_form }}
<table id="itens-table" class="table feito-table-0 itens-table">
  <thead>
    <tr>
      <th class="text-center" scope="col">#</th>
      <th class="text-center" scope="col">Código</th>
      <th class="text-center" scope="col">Descrição</th>
      <th class="text-center" scope="col">Quantidade</th>
      <th class="text-center" scope="col">Unidade</th>
      <th class="text-center" scope="col">Custo Unit.</th>
      <th class="text-center" scope="col">Custo Total</th>

    </tr>
  </thead>
  <tbody>
    {% for it in formset %}
      <tr>
        <td style="display: none" >{{ it.item_id }}</td>
        <td style="display: none" >{{ it.source }}</td>
        <th class="text-center" scope="row">{{ forloop.counter }}</th>
        <td class="text-center">{{ it.cod }}</td>
        <td class="text-center">{{ it.desc }}</td>
        <td class="text-center">{{ it.qtd_programada }}</td>
        <td class="text-center">{{ it.unid }}</td>
        <td class="text-center">{{ it.custo_unit}}</td>
        <td class="text-center">{{ it.custo_tot }}</td>

        <td class="text-center">
          <!-- Update book buttons -->
          <button type="submit" class="btn btn-sm btn-primary" >
            <span class="fa fa-pencil"></span>
          </button>
          <!-- Delete book buttons -->
          <button type="button" class="delete-item btn btn-sm btn-danger" >
            <span class="fa fa-trash"></span>
          </button>
        </td>
        <div id="divCheckbox" style="display: none;">        
          <td style="display: none;" >{{ it.item_id }}</td>
        </div>
      </tr>
    {% endfor %}
  </tbody>
</table>

producao/templates/producao/op_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'select2/css/select2.css' %}">
    <link rel="stylesheet" href="{% static 'autocomplete_light/select2.css' %}">
    <link href="{% static '/css/feito.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}

<div class="jumbotron">
    <form method="post" id="form">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-6 mb-0">
                <h1>Ordem de produção</h1 >
            </div>

            <div class="form-group col-md-6 mb-0">
                <button type="submit" name="act" value="save" class="btn btn-primary">Salvar</button>
                <a href="/pr/op/new"> <button type="button" class="btn btn-primary">Novo</button></a>
                <a href="/pr/op/list"> <button type="button" class="btn btn-primary">Pesquisar</button></a>
                <button type="button" id="delete" class="btn btn-primary">Deletar</button>
                <button type="button" name="rptop" id="imprime-op" class="btn btn-primary">Imprimir</button>
                <button type="button" name="producao" id="producao" class="btn btn-primary">Produção</button>
                <button type="button" class="btn btn-primary btn-search-prod" data-toggle="modal" data-target="#producao_save">Lançar Produção</button>    
            </div>
        </div>

        <div class="form-row">

            <div class="form-group col-md-2 mb-0">
                {{ form.num|as_crispy_field }}
            </div>
            <div class="form-group col-md-2 mb-0 ">
                {{ form.data_emissao|as_crispy_field }}
            </div>
            <div class="form-group col-md-2 mb-0">
                {{ form.data_previsao|as_crispy_field }}
            </div>
            <div class="form-group col-md-2 mb-0">
                {{ form.tempo_estimado|as_crispy_field }}
            </div>
            <div class="form-group col-md-2 mb-0">
                {{ form.tempo_realizado|as_crispy_field }}
            </div>
            <div class="form-group col-md-2 mb-0">
                {{ form.status|as_crispy_field }}
            </div>
        </div>
 
        <div class="form-row">
 
            <div class="form-group col-md-6 mb-0">
                {{ form.produto|as_crispy_field }}
            </div>
            <div class="form-group col-md-3 mb-0 " >
                {{ form.qtd_programada|as_crispy_field }}
            </div>
            <div class="form-group col-md-3 mb-0">
                {{ form.qtd_realizada|as_crispy_field }}
            </div>


        </div>

        <div class="form-row">    

            <div class="form-group col-md-3 mb-0 " >
                {{ form.momento_ini|as_crispy_field }}
            </div>
            <div class="form-group col-md-3 mb-0">
                {{ form.momento_fim|as_crispy_field }}
            </div>

            <div class="form-group col-md-3 mb-0">
                {{ form.setor_produtivo|as_crispy_field }}
            </div>

        </div>


        <div class="form-row">
            <div class="form-group col-md-2 mb-0">
                <button type="button" class="btn btn-primary btn-search-prod" data-toggle="modal" data-target="#prod_search">Pesquisar Produtos</button>                
            </div>
        </div>

        <div id="op_comp_fis_table">
            {% include "producao/op_comp_fis_table.html" %}
        </div>


        <div class="form-row">
            <div id="op_comp_fis_table">
                {% include "producao/op_comp_serv_int_table.html" %}
            </div>
        </div>




        <div class="form-row">
            <div id="op_comp_fis_table">
                {% include "producao/op_comp_serv_ext_table.html" %}
            </div>
        </div>


        <div id="op_producao_save">
            {% include "producao/op_production_add.html" %}
        </div>



        <div class="form-row" >
            <div class="form-group col-md-12 mb-0">
                <div id="fr-id">{{ id }}</div>
            </div>
        </div>
        
        

    </form>


       
    {% for error_field, error_message in form.errors.items %}
        <div class="alert alert-primary" role="alert"></div>
            <p>{{ error_field|striptags }}: {{ error_message|striptags }}</p>
        </div>
    {% endfor %}
      
    <div id="rptop">
    <div> 
    

</div>



<!-- {% include "prod/produto_search.html" %} -->
{% include "prod/_modal.html" %}



 
{% endblock content %}


{% block extrascripts %}


{{ form.media }}
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.full.js"></script> 



<script>
var tipoProduto = ""

function prod_selected(id){
    alert('entrei ' + '{{id}}')
    const formData = new FormData();
    formData.append('produto', id);
    formData.append('id', '{{ id }}');
    formData.append('tipo', tipoProduto);
    formData.append('csrfmiddlewaretoken', '{{ csrf_token }}');
    fetch("{% url 'producao:op_comp_fis_add' %}", {
        method: 'POST',
        body: formData
    })
    .then(response => response.json())
    .then(data => {
        location.reload();
    })
    .catch(error => {
        console.error('Error:', error.message);
    });
}


jQuery.noConflict();
jQuery(document).ready(function( $ ) {



    jQuery.noConflict()(".itens-table").on("click", ".delete-item", function(event){
        event.preventDefault();
        var currentRow = $(this).closest("tr"); 
        var item_id = currentRow.find("td:eq(0) input").val();
        var source = currentRow.find("td:eq(1) input").val();
        $.ajax({
            type: "POST",
            url: "{% url 'producao:op_delitem' %}",
            data: {"item_id": item_id, "source": source , csrfmiddlewaretoken: '{{ csrf_token }}'},
            success: function(result){
                location.reload();
            },
            error: function(error){
                alert("Não foi possivel completar o processo")
            }
        });
    }); 

    jQuery.noConflict()("#delete").click(function(event){
        var fr_id = $("#fr-id").text();
        $.ajax({
            type: "GET",
            url: "{% url 'entradas:nf_entrada_delete' %}",
            data: {"id": fr_id},
            success: function(result){
                alert("Nota Excluído com sucesso")
            },
            error: function(error){
                alert("A Nota não pode ser excluído")
            }
        })
    })


    jQuery.noConflict()("#BX").click(function(event){
        var fr_id = $("#fr-id").text();
        var fr_data = $("#id_data_producao").val();
        var fr_qtd_produzida = $("#id_qtd_producao").val();
        var fr_qtd_perdida = $("#id_qtd_perdida").val();
        var fr_encerrar = $("#encerrar").val()

        $.ajax({
            type: "GET",
            url: "{% url 'producao:prod_save' %}",
            data: {"op_id": fr_id,
                    "data": fr_data,
                    "qtd_produzida": fr_qtd_produzida,
                    "qtd_perdida": fr_qtd_perdida
            },
            success: function(result){
                $("#id_data_producao").val('');
                $("#id_qtd_producao").val('');
                $("#id_qtd_perdida").val('');
                $("#id_encerrar").val(false);
                $("#producao_save").modal('toggle');
                location.reload();
            },
            error: function(error){
                alert("Erro na gravação")
            }
        })
    })


    jQuery.noConflict()("#imprime-op").click(function(event){
        var fr_id = $("#fr-id").text();
        var url = "{% url 'producao:rpt_op' %}"

        $.ajax({
            type: "GET",
            url: "{% url 'producao:rpt_op' %}",
            data: {"op_id": fr_id,

            },
            success: function(response) {
                    var w = window.open('about:blank');
                    w.document.open();
                    w.document.write(response);
                    w.document.close();
                },
            error: function(error){
                alert("Erro na gravação")
            }
        })
    })

})
</script>






{% endblock extrascripts %}

producao/templates/producao/op_list_table.html
<table id="list-table" class="table">
    <thead>
    <tr>
      <th class="text-center" scope="col">#</th>
      <th class="text-center" scope="col">Número</th>
      <th class="text-center" scope="col">Data de Emissão</th>
      <th class="text-center" scope="col">Status</th>
      <th class="text-center" scope="col">Operacao</th>
      <th class="text-center" scope="col">Fornecedor</th>
      <th class="text-center" scope="col">Valor da nota</th>
      <th class="text-center" scope="col">Obs</th>
      <th class="text-center" scope="col">Read / Update / Delete</th>
    </tr>
    </thead>
    <tbody>
    {% for it in lista %}
      <tr>
        <th class="text-center" scope="row">{{ forloop.counter }}</th>
        <td class="text-center">{{ it.num }}</td>
        <td class="text-center">{{ it.data_emissao|date:"SHORT_DATE_FORMAT"}}</td>
        <td class="text-center">{{ it.status }}</td>
        <td class="text-center">{{ it.operacao }}</td>
        <td class="text-center">{{ it.parceiro }}</td>
        <td class="text-center">{{ it.valor_total_nota }}</td>
        <td class="clamp">{{ it.obs }}</td>
        <td class="text-center">
          <!-- Read book buttons -->
          <button type="button" class="read btn btn-sm btn-primary" data-form-url="{% url 'entradas:nf_entrada_read' it.pk %}">
            <span class="fa fa-eye"></span>
          </button>
          <!-- open pedido full -->
          <button type="button" id='detail' class="detail btn btn-sm btn-primary" data-form-url="{% url 'entradas:nf_entrada_detail' it.pk %}" >
            <span class="fa fa-pencil"></span>
          </button>
        </td>
      </tr>
    {% endfor %}
  
    </tbody>
  </table>