core/urls.py
from django.urls import path
from . import views as v

app_name = 'core'

urlpatterns = [
    path('', v.index, name='index'),
]

feito/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'Sistema Gerencial DEFER'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('core.urls')),
    path('prod/', include('prod.urls')),
    path('cyber/', include('cyber_sinc.urls')),
    path('com/', include('comercial.urls')),
    path('cad/', include('cadastro.urls')),
    path('pop/', include('modalform.urls')),
    path('fin/', include('financeiro.urls')),
    path('ent/', include('entradas.urls')),
    path('est/', include('estoque.urls')),
    path('pr/', include('producao.urls')),
    path('rel/', include('reports.urls')),
    path('caixa/', include('caixa.urls')),
    
]

modalform/urls.py
from django.urls import path

from . import views

app_name = 'modalform'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('filter/', views.BookFilterView.as_view(), name='filter_book'),
    path('create/', views.BookCreateView.as_view(), name='create_book'),
    path('update/<int:pk>', views.BookUpdateView.as_view(), name='update_book'),
    path('read/<int:pk>', views.BookReadView.as_view(), name='read_book'),
    path('delete/<int:pk>', views.BookDeleteView.as_view(), name='delete_book'),
    path('books/', views.books, name='books'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

modalform/models.py
from django.db import models


class Book(models.Model):
    HARDCOVER = 1
    PAPERBACK = 2
    EBOOK = 3
    BOOK_TYPES = (
        (HARDCOVER, 'Hardcover'),
        (PAPERBACK, 'Paperback'),
        (EBOOK, 'E-book'),
    )
    title = models.CharField(max_length=50)
    publication_date = models.DateField(null=True)
    author = models.CharField(max_length=30, blank=True)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    pages = models.IntegerField(blank=True, null=True)
    book_type = models.PositiveSmallIntegerField(choices=BOOK_TYPES)

    timestamp = models.DateField(auto_now_add=True, auto_now=False)

modalform/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from bootstrap_modal_forms.forms import BSModalModelForm, BSModalForm
from bootstrap_modal_forms.mixins import PopRequestMixin, CreateUpdateAjaxMixin
from .models import Book


class BookFilterForm(BSModalForm):
    type = forms.ChoiceField(choices=Book.BOOK_TYPES)

    class Meta:
        fields = ['type']


class BookModelForm(BSModalModelForm):
    publication_date = forms.DateField(
        error_messages={'invalid': 'Enter a valid date in YYYY-MM-DD format.'}
    )

    class Meta:
        model = Book
        exclude = ['timestamp']


class CustomUserCreationForm(PopRequestMixin, CreateUpdateAjaxMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']

modalform/views.py
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views import generic

from bootstrap_modal_forms.generic import (
    BSModalLoginView,
    BSModalFormView,
    BSModalCreateView,
    BSModalUpdateView,
    BSModalReadView,
    BSModalDeleteView
)

from .forms import (
    BookModelForm,
    CustomUserCreationForm,
    CustomAuthenticationForm,
    BookFilterForm
)
from .models import Book

class Logout(generic.ListView):
    pass


class Index(generic.ListView):
    model = Book
    context_object_name = 'books'
    template_name = 'modalform/index.html'

    def get_queryset(self):
        qs = super().get_queryset()
        if 'type' in self.request.GET:
            qs = qs.filter(book_type=int(self.request.GET['type']))
        return qs


class BookFilterView(BSModalFormView):
    template_name = 'modalform/filter_book.html'
    form_class = BookFilterForm

    def form_valid(self, form):
        self.filter = '?type=' + form.cleaned_data['type']
        response = super().form_valid(form)
        return response

    def get_success_url(self):
        return reverse_lazy('modalform:index') + self.filter


class BookCreateView(BSModalCreateView):
    template_name = 'modalform/create_book.html'
    form_class = BookModelForm
    success_message = 'Success: Book was created.'
    success_url = reverse_lazy('modalform:index')


class BookUpdateView(BSModalUpdateView):
    model = Book
    template_name = 'modalform/update_book.html'
    form_class = BookModelForm
    success_message = 'Success: Book was updated.'
    success_url = reverse_lazy('modalform:index')


class BookReadView(BSModalReadView):
    model = Book
    template_name = 'modalform/read_book.html'


class BookDeleteView(BSModalDeleteView):
    model = Book
    template_name = 'modalform/delete_book.html'
    success_message = 'Success: Book was deleted.'
    success_url = reverse_lazy('modalform:index')


class SignUpView(BSModalCreateView):
    form_class = CustomUserCreationForm
    template_name = 'modalform/signup.html'
    success_message = 'Success: Sign up succeeded. You can now Log in.'
    success_url = reverse_lazy('modalform:index')


class CustomLoginView(BSModalLoginView):
    authentication_form = CustomAuthenticationForm
    template_name = 'examples/login.html'
    success_message = 'Success: You were successfully logged in.'
    success_url = reverse_lazy('index')


def books(request):
    data = dict()
    if request.method == 'GET':
        books = Book.objects.all()
        data['table'] = render_to_string(
            '_books_table.html',
            {'books': books},
            request=request
        )
        return JsonResponse(data)

modalform/templates/_books_table.html
<table id="books-table" class="table">
  <thead>
  <tr>
    <th class="text-center" scope="col">#</th>
    <th class="text-center" scope="col">Title</th>
    <th class="text-center" scope="col">Author</th>
    <th class="text-center" scope="col">Type</th>
    <th class="text-center" scope="col">Publication date</th>
    <th class="text-center" scope="col">Pages</th>
    <th class="text-center" scope="col">Price (€)</th>
    <th class="text-center" scope="col">Read / Update / Delete</th>
  </tr>
  </thead>
  <tbody>
  {% for book in books %}
    <tr>
      <th class="text-center" scope="row">{{ forloop.counter }}</th>
      <td class="text-center">{{ book.title }}</td>
      <td class="text-center">{{ book.author }}</td>
      <td class="text-center">{{ book.get_book_type_display }}</td>
      <td class="text-center">{{ book.publication_date }}</td>
      <td class="text-center">{{ book.pages }}</td>
      <td class="text-center">{{ book.price }}</td>
      <td class="text-center">
        <!-- Read book buttons -->
        <button type="button" class="read-book btn btn-sm btn-primary" data-form-url="{% url 'modalform:read_book' book.pk %}">
          <span class="fa fa-eye"></span>
        </button>
        <!-- Update book buttons -->
        <button type="button" class="update-book btn btn-sm btn-primary" data-form-url="{% url 'modalform:update_book' book.pk %}">
          <span class="fa fa-pencil"></span>
        </button>
        <!-- Delete book buttons -->
        <button type="button" class="delete-book btn btn-sm btn-danger" data-form-url="{% url 'modalform:delete_book' book.pk %}">
          <span class="fa fa-trash"></span>
        </button>
      </td>
    </tr>
  {% endfor %}

  </tbody>
</table>

modalform/templates/_footer.html
<footer class="footer" style="border-top: 1px solid #eee;">
  <div class="container">
    <p class="text-muted mt-3">django-bootstrap-modal-forms
    </p>
  </div>
</footer>

modalform/templates/_header.html
{% load static %}

<!-- Header -->
<header style="border-bottom: 1px solid #eee;">
  <!-- Messages -->
  <div>
    {% if messages %}
      {% for message in messages %}
        <div style="border-radius:0;" {% if message.tags %} class="alert alert-icon alert-{{ message.tags }} alert-dismissible fade show mb-0" role="alert" {% endif %}>
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endfor %}
    {% endif %}
  </div>
  <!-- End Messages -->
  <div class="container">
    <!-- Navbar -->
    <!-- Important: columns can be used directly in navbar since it is d-flex -->
    <nav class="navbar navbar-expand-md navbar-light p-0 py-2">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <h1>
              <a class="nav-link p-0" href="/">django-bootstrap-modal-forms
                <span class="sr-only">(current)</span></a>
            </h1>
          </li>
        </ul>
        <p class="text-muted ml-auto m-0">Created and maintained by
          <a href="https://github.com/trco" target="_blank" style="text-decoration: none;">
            <svg style="margin-bottom: -3px; margin-right: 2px;" viewbox="0 0 64 64" width="16" height="16">
              <path
                stroke-width="0"
                fill="currentColor"
                d="M32 0 C14 0 0 14 0 32 0 53 19 62 22 62 24 62 24 61 24 60 L24 55 C17 57 14 53 13 50 13 50 13 49 11 47 10 46 6 44 10 44 13 44 15 48 15 48 18 52 22 51 24 50 24 48 26 46 26 46 18 45 12 42 12 31 12 27 13 24 15 22 15 22 13 18 15 13 15 13 20 13 24 17 27 15 37 15 40 17 44 13 49 13 49 13 51 20 49 22 49 22 51 24 52 27 52 31 52 42 45 45 38 46 39 47 40 49 40 52 L40 60 C40 61 40 62 42 62 45 62 64 53 64 32 64 14 50 0 32 0 Z"></path>
            </svg>
          </a>
          <a href="https://github.com/trco" target="_blank">trco</a>
        </p>
      </div>
    </nav>
    <!-- End Navbar -->
  </div>
</header>
<!-- End Header -->

modalform/templates/_modal.html
<div class="modal fade" id="create-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog mt-5">
    <div class="modal-content">
    </div>
  </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog mt-5" role="document">
    <div class="modal-content"></div>
  </div>
</div>

modalform/templates/base2.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">

    {% block stylesheets %}
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
      <!-- Font awesome CSS -->
      <link rel="stylesheet" href="{% static 'assets/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
      <!-- Custom CSS -->
      <style media="screen">
        .invalid {
          color: #dc3545;
          font-size: 80%;
        }
        body {
          display: flex;
          flex-direction: column;
          min-height: 100vh;
        }
        .footer {
          margin: auto 0 0;
          height: 56px;
        }
      </style>
    {% endblock stylesheets %}

    <title>django-bootstrap-modal-forms</title>
  </head>

  <body>

    <!-- Includes -->
    {% include "_header.html" %}

    {% block content %}{% endblock content %}

    <!-- Includes -->
    {% include "_footer.html" %}

    <!-- JavaScript -->
    {% block scripts %}
      <script src="{% static 'assets/js/jquery-3.2.1.min.js' %}"></script>
      <script src="{% static 'assets/js/popper.min.js' %}"></script>
      <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
      <!-- You can alternatively load the minified version -->
      <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
    {% endblock scripts %}

    {% block extrascripts %}{% endblock extrascripts %}

  </body>

</html>