core/urls.py
from django.urls import path
from . import views as v

app_name = 'core'

urlpatterns = [
    path('', v.index, name='index'),
]

feito/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'Sistema Gerencial DEFER'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('core.urls')),
    path('prod/', include('prod.urls')),
    path('cyber/', include('cyber_sinc.urls')),
    path('com/', include('comercial.urls')),
    path('cad/', include('cadastro.urls')),
    path('pop/', include('modalform.urls')),
    path('fin/', include('financeiro.urls')),
    path('ent/', include('entradas.urls')),
    path('est/', include('estoque.urls')),
    path('pr/', include('producao.urls')),
    path('rel/', include('reports.urls')),
    path('caixa/', include('caixa.urls')),
    
]

modalform/urls.py
from django.urls import path

from . import views

app_name = 'modalform'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('filter/', views.BookFilterView.as_view(), name='filter_book'),
    path('create/', views.BookCreateView.as_view(), name='create_book'),
    path('update/<int:pk>', views.BookUpdateView.as_view(), name='update_book'),
    path('read/<int:pk>', views.BookReadView.as_view(), name='read_book'),
    path('delete/<int:pk>', views.BookDeleteView.as_view(), name='delete_book'),
    path('books/', views.books, name='books'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

modalform/models.py
from django.db import models


class Book(models.Model):
    HARDCOVER = 1
    PAPERBACK = 2
    EBOOK = 3
    BOOK_TYPES = (
        (HARDCOVER, 'Hardcover'),
        (PAPERBACK, 'Paperback'),
        (EBOOK, 'E-book'),
    )
    title = models.CharField(max_length=50)
    publication_date = models.DateField(null=True)
    author = models.CharField(max_length=30, blank=True)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    pages = models.IntegerField(blank=True, null=True)
    book_type = models.PositiveSmallIntegerField(choices=BOOK_TYPES)

    timestamp = models.DateField(auto_now_add=True, auto_now=False)

modalform/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from bootstrap_modal_forms.forms import BSModalModelForm, BSModalForm
from bootstrap_modal_forms.mixins import PopRequestMixin, CreateUpdateAjaxMixin
from .models import Book


class BookFilterForm(BSModalForm):
    type = forms.ChoiceField(choices=Book.BOOK_TYPES)

    class Meta:
        fields = ['type']


class BookModelForm(BSModalModelForm):
    publication_date = forms.DateField(
        error_messages={'invalid': 'Enter a valid date in YYYY-MM-DD format.'}
    )

    class Meta:
        model = Book
        exclude = ['timestamp']


class CustomUserCreationForm(PopRequestMixin, CreateUpdateAjaxMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']

modalform/views.py
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views import generic

from bootstrap_modal_forms.generic import (
    BSModalLoginView,
    BSModalFormView,
    BSModalCreateView,
    BSModalUpdateView,
    BSModalReadView,
    BSModalDeleteView
)

from .forms import (
    BookModelForm,
    CustomUserCreationForm,
    CustomAuthenticationForm,
    BookFilterForm
)
from .models import Book

class Logout(generic.ListView):
    pass


class Index(generic.ListView):
    model = Book
    context_object_name = 'books'
    template_name = 'modalform/index.html'

    def get_queryset(self):
        qs = super().get_queryset()
        if 'type' in self.request.GET:
            qs = qs.filter(book_type=int(self.request.GET['type']))
        return qs


class BookFilterView(BSModalFormView):
    template_name = 'modalform/filter_book.html'
    form_class = BookFilterForm

    def form_valid(self, form):
        self.filter = '?type=' + form.cleaned_data['type']
        response = super().form_valid(form)
        return response

    def get_success_url(self):
        return reverse_lazy('modalform:index') + self.filter


class BookCreateView(BSModalCreateView):
    template_name = 'modalform/create_book.html'
    form_class = BookModelForm
    success_message = 'Success: Book was created.'
    success_url = reverse_lazy('modalform:index')


class BookUpdateView(BSModalUpdateView):
    model = Book
    template_name = 'modalform/update_book.html'
    form_class = BookModelForm
    success_message = 'Success: Book was updated.'
    success_url = reverse_lazy('modalform:index')


class BookReadView(BSModalReadView):
    model = Book
    template_name = 'modalform/read_book.html'


class BookDeleteView(BSModalDeleteView):
    model = Book
    template_name = 'modalform/delete_book.html'
    success_message = 'Success: Book was deleted.'
    success_url = reverse_lazy('modalform:index')


class SignUpView(BSModalCreateView):
    form_class = CustomUserCreationForm
    template_name = 'modalform/signup.html'
    success_message = 'Success: Sign up succeeded. You can now Log in.'
    success_url = reverse_lazy('modalform:index')


class CustomLoginView(BSModalLoginView):
    authentication_form = CustomAuthenticationForm
    template_name = 'examples/login.html'
    success_message = 'Success: You were successfully logged in.'
    success_url = reverse_lazy('index')


def books(request):
    data = dict()
    if request.method == 'GET':
        books = Book.objects.all()
        data['table'] = render_to_string(
            '_books_table.html',
            {'books': books},
            request=request
        )
        return JsonResponse(data)

modalform/templates/modalform/create_book.html
{% load widget_tweaks %}

<form method="post" action="" novalidate>
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Create Book</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-primary">Create</button>
  </div>

</form>

modalform/templates/modalform/delete_book.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Delete Book</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <p class="delete-text">Are you sure you want to delete book with title
      <strong>{{ book.title }}</strong>?</p>
  </div>

  <div class="modal-footer">
    <button type="submit" id="delete-btn" class="btn btn-danger">Delete</button>
  </div>

</form>

modalform/templates/modalform/filter_book.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Filter Books</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>


  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>


  <div class="modal-footer">
    <button type="submit" class="btn btn-primary">Filter</button>
  </div>

</form>

modalform/templates/modalform/index.html
{% extends 'base.html' %}

{% block content %}

  {% include "_modal.html" %}

  <div class="container mt-3">
    <div class="row">
      <div class="col">
        <p class="text-primary">A jQuery plugin for creating AJAX driven Django forms in Bootstrap modal.</p>
        <h4>
          <strong>1. Signup form</strong>
        </h4>
        <p>Sign up via Bootstrap modal.</p>
        <div class="row">
          <div class="col-12 mb-3">
            <button id="signup-btn" class="btn btn-primary" type="button" name="button">Sign up</button>
          </div>
        </div>
        <h4>
          <strong>2. Login form</strong>
        </h4>
        <p>Log in via Bootstrap modal. Sign up first.</p>
        <div class="row">


        </div>
        <h4>
          <strong>3. CRUD actions</strong>
        </h4>
        <p>Create, Read, Update and Delete books in Bootstrap modal.</p>

        <div class="row">
          <div class="col-12 mb-3">
            <button id="create-book-sync" class="btn btn-primary" type="button" name="button">
              <span class="fa fa-plus mr-2"></span>Create book - Synchronous
            </button>
            <button id="create-book-async" class="btn btn-primary" type="button" name="button">
              <span class="fa fa-plus mr-2"></span>Create book - Asynchronous
            </button>
            <button id="filter-book" class="filter-book btn btn-primary" type="button" name="button" data-form-url="{% url 'modalform:filter_book' %}">
              <span class="fa fa-filter mr-2"></span>Filter books
            </button>
          </div>
          <div class="col-12 mb-3">
          {% if 'type' in request.GET %}
            <p class="filtered-books">Filtered books.</p>
          {% endif %}
          {% include "_books_table.html" %}
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

{% block extrascripts %}
  <script type="text/javascript">
      $(function () {
          // Login
          $("#login-btn").modalForm({
            formURL: "{% url 'modalform:login' %}"
          });

          //  Signup
          $("#signup-btn").modalForm({
            formURL: "{% url 'modalform:signup' %}"
          });

          // Create book synchronous
          function createBookSyncModalForm() {
            $("#create-book-sync").modalForm({
                formURL: "{% url 'modalform:create_book' %}",
                modalID: "#create-modal"
            });
          }
          createBookSyncModalForm();

          // Create book asynchronous button
          // message
          var asyncSuccessMessageCreate = [
            "<div ",
            "style='position:fixed;top:0;z-index:10000;width:100%;border-radius:0;' ",
            "class='alert alert-icon alert-success alert-dismissible fade show mb-0' role='alert'>",
            "Success: Book was created.",
            "<button type='button' class='close' data-dismiss='alert' aria-label='Close'>",
            "<span aria-hidden='true'>&times;</span>",
            "</button>",
            "</div>",
            "<script>",
            "$('.alert').fadeTo(2000, 500).slideUp(500, function () {$('.alert').slideUp(500).remove();});",
            "<\/script>"
          ].join("");

          // modal form
          function createBookAsyncModalForm() {
            $("#create-book-async").modalForm({
                formURL: "{% url 'modalform:create_book' %}",
                modalID: "#create-modal",
                asyncUpdate: true,
                asyncSettings: {
                  closeOnSubmit: true,
                  successMessage: asyncSuccessMessageCreate,
                  dataUrl: "books/",
                  dataElementId: "#books-table",
                  dataKey: "table",
                  addModalFormFunction: reinstantiateModalForms
                }
            });
          }
          createBookAsyncModalForm();

          // Update book asynchronous button
          // message
          var asyncSuccessMessageUpdate = [
            "<div ",
            "style='position:fixed;top:0;z-index:10000;width:100%;border-radius:0;' ",
            "class='alert alert-icon alert-success alert-dismissible fade show mb-0' role='alert'>",
            "Success: Book was updated.",
            "<button type='button' class='close' data-dismiss='alert' aria-label='Close'>",
            "<span aria-hidden='true'>&times;</span>",
            "</button>",
            "</div>",
            "<script>",
            "$('.alert').fadeTo(2000, 500).slideUp(500, function () {$('.alert').slideUp(500).remove();});",
            "<\/script>"
          ].join("");

          // modal form
          function updateBookModalForm() {
            $(".update-book").each(function () {
              $(this).modalForm({
                formURL: $(this).data("form-url"),
                asyncUpdate: true,
                asyncSettings: {
                  closeOnSubmit: false,
                  successMessage: asyncSuccessMessageUpdate,
                  dataUrl: "books/",
                  dataElementId: "#books-table",
                  dataKey: "table",
                  addModalFormFunction: reinstantiateModalForms
                }
              });
            });
          }
          updateBookModalForm();

          // Delete book buttons - formURL is retrieved from the data of the element
          function deleteBookModalForm() {
            $(".delete-book").each(function () {
                $(this).modalForm({formURL: $(this).data("form-url"), isDeleteForm: true});
            });
          }
          deleteBookModalForm();

          // Read book buttons
          function readBookModalForm() {
            $(".read-book").each(function () {
                $(this).modalForm({formURL: $(this).data("form-url")});
            });
          }
          readBookModalForm();

          function reinstantiateModalForms() {
            createBookAsyncModalForm();
            readBookModalForm();
            updateBookModalForm();
            deleteBookModalForm();
          }

          // Filter books button
          $("#filter-book").each(function () {
              $(this).modalForm({formURL: $(this).data("form-url")});
          });

          // Hide message
          $(".alert").fadeTo(2000, 500).slideUp(500, function () {
              $(".alert").slideUp(500);
          });
      });
  </script>
{% endblock extrascripts %}

modalform/templates/modalform/login.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Log in</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-primary" formnovalidate="formnovalidate">Log in</button>
  </div>

</form>

modalform/templates/modalform/read_book.html
{% load widget_tweaks %}

<div class="modal-header">
  <h3 class="modal-title">Book details</h3>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<div class="modal-body">

  <div class="">
    Title:
    {{ book.title }}
  </div>
  <div class="">
    Author:
    {{ book.author }}
  </div>
  <div class="">
    Price:
    {{ book.price }}
    €
  </div>
  <div class="">
    Pages:
    {{ book.pages }}
  </div>
  <div class="">
    Type:
    {{ book.get_book_type_display }}
  </div>
  <div class="">
    Publication date:
    {{ book.publication_date }}
  </div>

</div>

<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>

modalform/templates/modalform/signup.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Sign up</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-primary" formnovalidate="formnovalidate">Sign up</button>
  </div>

</form>

modalform/templates/modalform/update_book.html
{% load widget_tweaks %}

<form method="post" action="" novalidate>
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Update Book</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-primary">Update</button>
  </div>

</form>