comercial/urls.py
from django.urls import path

from . import views as v

app_name = 'comercial'

urlpatterns = [
    #path('', v.pedidos_list, name = 'pedidos_list'),
    path('detail/<ped_id>', v.pedido_detail, name = 'pedido_detail'),
    path('read/<int:pk>', v.Pedido_read.as_view(), name = 'pedido_read'),
    path('update/<int:pk>', v.Pedido_update.as_view(), name='pedido_update'),
    path('delete/<int:pk>', v.Pedido_delete.as_view(), name='pedido_delete'),
    path('filter/', v.Pedido_filter.as_view(), name='pedido_filter'),
    path('create/', v.Pedido_create.as_view(), name='pedido_create'),
    path('new/search_table', v.pedidos_prod_search_table, name='pedidos_prod_search_table'),
    path('pedidos/', v.pedidos, name='pedidos'),
    path('pedido_add_item/', v.Pedido_add_item.as_view(), name='pedido_add_item'),
    
    #Pedido
    path('pedido/list/', v.pedidos_list, name = 'pedidos_list'),
    path('pedido/new/', v.pedido_new, name='pedido_new'),
    path('pedido_detail/<pedido_id>', v.pedido_detail, name = 'pedido_detail'),
    path('pedido_full/search/', v.pedidos_prod_search, name='pedidos_prod_search'),
    path('pedido_full/prod_selected/', v.pedido_item_add, name='pedido_item_add'),
    path('pedido_full/item_delete/', v.pedido_item_delete, name='pedido_item_delete'),
    path('pedido_full/create/', v.pedido_new, name='pedido_new'),
    path('pedido_full/entrega_add/', v.pedido_entrega_add, name='pedido_entrega_add'),
    path('pedido_full/lote/', v.pedido_lote, name='pedido_lote'),
    #path('pedido_full/testaJson/', v.pedido_testaJson, name='pedido_testaJson'),

    #Orçamento
    path('orcamento/new/', v.orcamento_new, name='orcamento_new'),
    path('orcamento/list/', v.orcamento_list, name='orcamento_list'),
    path('orcamento/detail/<orcamento_id>', v.orcamento_detail, name = 'orcamento_detail'),
    path('orcamento/prod_search', v.orcamento_prod_search, name = 'orcamento_prod_search'),
    path('orcamento/item_add', v.orcamento_item_add, name = 'orcamento_item_add'),
    path('orcamento/item_delete', v.orcamento_item_delete, name = 'orcamento_item_delete'),
    path('orcamento/delete/', v.orcamento_delete, name = 'orcamento_delete'),
    path('orcamento/pedido_add', v.orcamento_pedido_add, name = 'orcamento_pedido_add'),
    
    #Entega
    path('entrega/new/', v.entrega_new, name='entrega_new'),
    path('entrega/list/', v.entrega_list, name='entrega_list'),
    path('entrega/detail/<entrega_id>', v.entrega_detail, name = 'entrega_detail'),
    path('entrega/prod_search', v.entrega_prod_search, name = 'entrega_prod_search'),
    path('entrega/item_add', v.entrega_item_add, name = 'entrega_item_add'),
    path('entrega/item_delete', v.entrega_item_delete, name = 'entrega_item_delete'),
    path('entrega/delete/', v.entrega_delete, name = 'entrega_delete'),
    path('entrega/pre_nota_add', v.pre_nota_add, name = 'pre_nota_add'),
    path('entrega/pre_nota_retorno', v.pre_nota_retorno, name = 'pre_nota_retorno'),
    path('entrega/pre_nota_estorno', v.pre_nota_estorno, name = 'pre_nota_estorno'),
    path('entrega/label', v.label, name = 'label'),
]

core/urls.py
from django.urls import path
from . import views as v

app_name = 'core'

urlpatterns = [
    path('', v.index, name='index'),
]

entradas/urls.py
from django.urls import path

from . import views as v

app_name = 'entradas'

urlpatterns = [
    #Notas de entrada
    path('nf/list', v.nf_entrada_list, name = 'nf_entrada_list'),
    path('nf/new', v.nf_entrada_new, name = 'nf_entrada_new'),
    path('nf/filter', v.nf_entrada_filter, name = 'nf_entrada_filter'),
    path('nf/read/<int:pk>', v.nf_entrada_read, name = 'nf_entrada_read'),
    path('nf/<int:pk>', v.nf_entrada_detail, name = 'nf_entrada_detail'),
    path('nf/prod_search', v.nf_entrada_prod_search, name = 'nf_entrada_prod_search'),
    path('nf/item_add', v.nf_entrada_item_add, name = 'nf_entrada_item_add'),
    path('nf/item_delete', v.nf_entrada_item_delete, name = 'nf_entrada_item_delete'),
    path('nf/delete/', v.nf_entrada_delete, name = 'nf_entrada_delete'),
    path('nf/parcelas/create', v.nf_entrada_parcelas_create, name = 'nf_entrada_parcelas_create'),
    path('nf/parcelas/delete', v.nf_entrada_parcelas_delete, name = 'nf_entrada_parcelas_delete'),
    path('nome-autocomplete/', v.NomeAutocomplete.as_view(), name='nome-autocomplete'), 
    path('transportadora-autocomplete/', v.TransportadoraAutocomplete.as_view(), name='transportadora-autocomplete'), 

    #Ordem de compra
    path('oc/list', v.oc_list, name = 'oc_list'),
    path('oc/new', v.oc_new, name = 'oc_new'),
    path('oc/<int:pk>', v.oc_detail, name = 'oc_detail'),
    path('oc/prod_search', v.oc_prod_search, name = 'oc_prod_search'),
    path('oc/item_add', v.oc_item_add, name = 'oc_item_add'),
    path('oc/item_delete', v.oc_item_delete, name = 'oc_item_delete'),
    path('oc/delete/', v.oc_delete, name = 'oc_delete'),
    path('oc/print', v.oc_print, name = 'oc_print'),
    path('oc/email', v.oc_email, name = 'oc_email'),
    path('oc/send_email', v.send_email, name = 'send_email'),
    path('oc/oc_pdf', v.oc_pdf, name = 'oc_pdf'),
    path('oc/reports', v.OC_reports.as_view()),

   
    #Solicitação de materiais
    path('sm/list', v.sm_list, name = 'sm_list'),
    path('sm/new', v.sm_new, name = 'sm_new'),
    path('sm/<int:pk>', v.sm_detail, name = 'sm_detail'),

]

feito/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'Sistema Gerencial DEFER'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('core.urls')),
    path('prod/', include('prod.urls')),
    path('cyber/', include('cyber_sinc.urls')),
    path('com/', include('comercial.urls')),
    path('cad/', include('cadastro.urls')),
    path('pop/', include('modalform.urls')),
    path('fin/', include('financeiro.urls')),
    path('ent/', include('entradas.urls')),
    path('est/', include('estoque.urls')),
    path('pr/', include('producao.urls')),
    path('rel/', include('reports.urls')),
    path('caixa/', include('caixa.urls')),
    
]

entradas/views.py
from getopt import gnu_getopt
from django.shortcuts import redirect, render, get_object_or_404
from django.template.loader import render_to_string
from django.http.response import HttpResponse
from django.forms import formset_factory
from .models import *
from .forms import *
from .reports import *
from django.db import transaction
from financeiro.models import Vencimento
from io import BytesIO
from core.rpt_linha_pdf import *
import core.label_pdf as lbl
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .filters import *

def nf_entrada_list(request):
    lista = NF_Filter(request.GET, queryset=NF_entrada.objects.all().order_by('-data_emissao'))
    paginator = Paginator(lista.qs, 20) # Show 25 contacts per page.
    page_number = request.GET.get('page', 1)

    try:
        page_obj = paginator.get_page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)

    return render(request, 'entradas/nf_entrada_list.html', {'page_obj': page_obj, 'lista': lista})

def nf_entrada_filter(request):

    lista = NF_entrada.objects.all().order_by('-data_emissao')
    paginator = Paginator(lista, 20) # Show 25 contacts per page.
    
    page_number = request.GET.get('page', 1)

    try:
        page_obj = paginator.get_page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)

    return render(request, 'entradas/nf_entrada_list.html', {'page_obj': page_obj })



def nf_entrada_new(request):
    print('nf_entrada_new/00')
    if request.method == "POST":
        print('nf_entrada_new/01')
        form = NF_entrada_detail_form(request.POST)
        if form.is_valid():
            print('nf_entrada_new/02')
            fr = form.save(commit=False)
            fr.save()
            return redirect('entradas:nf_entrada_detail', fr.id) 
        else:
            print('nf_entrada_new/03')
            return render(request, 'entradas/nf_entrada_detail.html', {'form': form})     
    else:
        print('nf_entrada_new/ 10')
        form = NF_entrada_detail_form()
        return render(request, 'entradas/nf_entrada_detail.html', {'form': form})   


class NomeAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        print('nome-autocomplete')
        if not self.request.user.is_authenticated:
            return Parceiro.objects.none()
        qs = Parceiro.objects.only('nome')
        if self.q:
            qs = qs.filter(nome__icontains=self.q)
        return qs

class TransportadoraAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        print('transportadora-autocomplete')
        if not self.request.user.is_authenticated:
            return Parceiro.objects.none()
        qs = Parceiro.objects.filter(tipo__sigla = 'T').only('nome')
        if self.q:
            qs = qs.filter(nome__icontains=self.q)
        return qs

def nf_entrada_prod_search(request):
    data = dict()    
    if request.method == 'GET':
        pesq = request.GET.get('pesquisa')
        prod = Prod.objects.only('id', 'cod', 'desc').filter(desc__istartswith = pesq)
        data['table'] = render_to_string(
            'comercial/_prod_table.html',   
            {'prods': prod},
        )
        print('Pesquisa: ' + pesq)
        return HttpResponse(data['table'])
    else:
        print('Prod search - ' + request.POST)
        return render(request, 'comercial/orcamento_prod_search.html' )


def nf_entrada_read(request, id):
    pass

@transaction.atomic
def nf_entrada_item_add(request):
    if request.method == 'GET':
        produto = request.GET.get('produto')
        id = request.GET.get('id')
        print(produto)
        print(id)
        nf = NF_entrada.objects.get(pk=id)
        prod = Prod.objects.get(pk=produto)
        nf_it = NF_entrada_itens()
        nf_it.nf_entrada = nf
        nf_it.produto = prod
        nf_it.save()

        return HttpResponse('Produto adicionado')
    else:
        return HttpResponse('nao é post')

def nf_entrada_parcelas_create(request):
    id = request.GET.get('id')
    print(id)
    nf = NF_entrada.objects.get(id = id)
    parcelas = Vencimento.objects.parcelas_create(nf.vencimento, nf.valor_total_nota, nf.data_emissao)
    print (parcelas)
    for p in parcelas:
        print(p)
        cp = Conta_pagar()
        cp.entrada = nf
        cp.nf = nf.num
        cp.parcela_num = p['numero']
        cp.data_emissao = nf.data_emissao
        cp.vencimento = p['vencimento']
        cp.valor_parcela = p['valor_parcela']
        cp.conta_caixa = nf.operacao.conta_caixa
        cp.save()
        
    formset_parc = formset_parcelas(nf = nf)
    data = dict()    
    data['table'] = render_to_string(
        'entradas/nf_entrada_parcelas_table.html',   
        {'formset_parcelas': formset_parc},
    )
    return HttpResponse(data['table'])
    

def nf_entrada_parcelas_delete(request):
    id = request.GET.get('id')
    Conta_pagar.objects.filter(entrada_id = id).delete()
    nf = NF_entrada.objects.get(id = id)
    formset_parc = formset_parcelas(nf = nf)
    data = dict()    
    data['table'] = render_to_string(
        'entradas/nf_entrada_parcelas_table.html',   
        {'formset_parcelas': formset_parc},
    )
    return HttpResponse(data['table'])


def nf_entrada_item_delete(request):
    id_item = request.GET.get('item_id')
    it = NF_entrada_itens.objects.get(pk=id_item)
    it.delete()
    return HttpResponse('Produto excluido')


def nf_entrada_delete(request):
    id = request.GET.get('id')
    nf = NF_entrada.objects.get(pk=id)
    nf.delete()

    #NF_entrada.objects.filter(pk=id).delete()
    return redirect('entradas:nf_entrada_list')

def formset_parcelas(**kwargs):
    nf_parcelas_formset = formset_factory(NF_entrada_parcelas_formset, NF_entrada_parcelas_BaseFormSet, extra=0)
    if kwargs.get('nf'):
        nf = kwargs.get('nf')
        nf_parcelas = nf.parcelas.all()
        nf_parcelas_initial = [{
            'parc_id': l.id,
            'num': l.parcela_num,
            'venc': l.vencimento,
            'valor': l.valor_parcela,  
            }for l in nf_parcelas] 
        formset_parcelas = nf_parcelas_formset(initial = nf_parcelas_initial)
        return formset_parcelas
    if kwargs.get('request'):
        request = kwargs.get('request')
        formset_parcelas = nf_parcelas_formset(request)
        if formset_parcelas.is_valid():
            print('formset_parcelas válido')
            for p in formset_parcelas:
                if p.cleaned_data.get('parc_id'):
                    parc_id = p.cleaned_data.get('parc_id')
                    parc_data = Conta_pagar.objects.get(id=parc_id)
                    parc_data.vencimento = p.cleaned_data.get('venc')
                    parc_data.valor_parcela = p.cleaned_data.get('valor')
                    parc_data.save()
                    #print(parc_data.entrada)
                    #print(p.cleaned_data.get('venc'))
            return True
        else:
            return False

def nf_entrada_detail(request, pk):
    nf = get_object_or_404(NF_entrada, pk=pk)
    nf_itens = NF_entrada_itens.objects.filter(nf_entrada = nf)
    nf_itens_formset = formset_factory(NF_entrada_itens_formset, NF_entrada_itens_BaseFormSet, extra=0 )    
    nf_itens_initial = [{
        'item_id': l.id,
        'cod': l.produto.cod,
        'desc': l.produto.desc, 
        'unid': l.produto.unid.unid, 
        'qtd': l.qtd, 
        'preco_unit': l.preco_unit, 
        'preco_tot':l.preco_tot,
        'aliq_icms': l.aliq_icms,
        'aliq_ipi': l.aliq_ipi,
        'valor_icms': l.valor_icms,
        'valor_ipi': l.valor_ipi,
        'valor_total_item': l.valor_total_item, 
        }for l in nf_itens] 
    formset = nf_itens_formset(initial = nf_itens_initial)    
    formset_parc = formset_parcelas(nf = nf)

    if request.method == 'POST':
        print('é post')
        form = NF_entrada_detail_form(request.POST, instance = nf)
        formset = nf_itens_formset(request.POST)
        
        if form.is_valid():
            print('form is valid')
            if formset.is_valid():
                print('formset is valid')
                nf = form.save(commit=False)
                nf.save()
                for it in formset:
                    if id:
                        item_id = it.cleaned_data.get('item_id')
                        #print(it.cleaned_data)
                        if item_id:
                            itens_data = NF_entrada_itens.objects.get(pk=item_id)
                            itens_data.qtd = it.cleaned_data.get('qtd')
                            itens_data.preco_unit = it.cleaned_data.get('preco_unit')
                            itens_data.aliq_icms = it.cleaned_data.get('aliq_icms')
                            itens_data.aliq_ipi = it.cleaned_data.get('aliq_ipi')
                            itens_data.save()

                if formset_parcelas(request = request.POST):
                    print('ok com parcelas')    
                    return redirect('entradas:nf_entrada_detail', nf.id)
                else:
                    print('erro em formset parcelas')
            else:
                print(formset.non_form_errors())
            
    else:
        form = NF_entrada_detail_form(instance  = nf)
    return render(request, 'entradas/nf_entrada_detail.html', {'form': form, 'formset': formset, 'formset_parcelas': formset_parc, 'id': nf.id})










#Ordem de compra

def oc_list(request):
    lista = Ordem_compra.objects.all()
    return render(request, 'entradas/oc_list.html', {'lista': lista})

def oc_new(request):
    print('nf_entrada_new/00')
    if request.method == "POST":
        print('nf_entrada_new/01')
        form =OC_detail_form(request.POST)
        if form.is_valid():

entradas/templates/entradas/oc_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}



{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'select2/css/select2.css' %}">
    <link rel="stylesheet" href="{% static 'autocomplete_light/select2.css' %}">
    <link href="{% static '/css/feito.css' %}" rel="stylesheet">
{% endblock css %}



{% block content %}
<div class="jumbotron">
    <form method="post" id="form">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-6 mb-0">
                <h1>Ordem de compra</h1 >
            </div>

            <div class="form-group col-md-6 mb-0">
                <button type="submit" name="act" value="save" class="btn btn-primary">Salvar</button>
                <a href="/ent/oc/new"> <button type="button" class="btn btn-primary">Novo</button></a>
                <a href="/ent/oc/list"> <button type="button" class="btn btn-primary">Pesquisar</button></a>
                <button type="button" id="delete" class="btn btn-primary">Deletar</button>
                <button type="button" name="imprimir" id="imprimir" class="btn btn-primary">Imprimir</button>
                <button type="button" name="email_modal" id="email_modal" class="btn btn-primary">Email</button>
                <button type="button" name="modal_teste" id="modal_teste" class="btn btn-primary">TEste</button>
                <button type="button" name="oc_pdf" id="oc_pdf" class="btn btn-primary">PDF</button>


            </div>
        </div>

        <div class="form-row">

            <div class="form-group col-md-1 mb-0">
                {{ form.num|as_crispy_field }}
            </div>
            <div class="form-group col-md-1 mb-0 " >
                {{ form.data_emissao|as_crispy_field }}
            </div>
            <div class="form-group col-md-2 mb-0">
                {{ form.operacao|as_crispy_field }}
            </div>
            <div class="form-group col-md-2 mb-0">
                {{ form.status|as_crispy_field }}
            </div>
            <div class="form-group col-md-2 mb-0">
                {{ form.prazo_entrega|as_crispy_field }}
            </div>
            <div class="form-group col-md-2 mb-0">
                {{ form.data_previsao|as_crispy_field }}
            </div>
            <div class="form-group col-md-2 mb-0">
                {{ form.vencimento|as_crispy_field }}
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6 mb-0">
                {{ form.parceiro|as_crispy_field }}
            </div>

            <div class="form-group col-md-6 mb-0">
                {{ form.transportadora|as_crispy_field }}
            </div>
        </div>

        <div class="form-row">    
            <div class="form-group col-md-2 mb-0">
                {{ form.valor_total_produtos|as_crispy_field }}
            </div>
            <div class="form-group col-md-2 mb-0">
                {{ form.valor_frete|as_crispy_field }}
            </div>          
            <div class="form-group col-md-2 mb-0">
                {{ form.valor_outras_desp|as_crispy_field }}
            </div>
            <div class="form-group col-md-2 mb-0">
                {{ form.valor_seguro|as_crispy_field }}
            </div>
            <div class="form-group col-md-2 mb-0">
                {{ form.desconto|as_crispy_field }}
            </div>
            <div class="form-group col-md-2 mb-0">
                {{ form.valor_ipi|as_crispy_field }}
            </div>

        </div>

        <div class="form-row">  
            <div class="form-group col-md-3 mb-0">
                {{ form.valor_icms|as_crispy_field }}
            </div>
            <div class="form-group col-md-2 mb-0">
                {{ form.base_calc_icms|as_crispy_field }}
            </div>
            <div class="form-group col-md-2 mb-0">
                {{ form.base_calc_icms_st|as_crispy_field }}
            </div>
            <div class="form-group col-md-2 mb-0">
                {{ form.valor_icms_st |as_crispy_field }}
            </div>
            <div class="form-group col-md-3 mb-0">
                {{ form.valor_total_oc|as_crispy_field }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-2 mb-0">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#pesquisa-prod">Pesquisar Produtos</button>
            </div>
        </div>

        <div id="orcamento-itens">
            {% include "entradas/oc_itens_table.html" %}
        </div>
        



        <div class="form-row" >
            <div class="form-group col-md-12 mb-0">
                <div id="fr-id">{{ id }}</div>
                <div id="prod-selected"></div>
                <div id="ocprint"></div>
            </div>
        </div>
        
    </form>


       
    {% for error_field, error_message in form.errors.items %}
        <div class="alert alert-primary" role="alert"></div>
            <p>{{ error_field|striptags }}: {{ error_message|striptags }}</p>
        </div>
    {% endfor %}
      
    
    

</div>



{% include "entradas/nf_entrada_prod_search.html" %}

{% include "entradas/email.html" %}

 
{% endblock content %}


{% block extrascripts %}


{{ form.media }}
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.full.js"></script> 

<script>
(function ($) {
    jQuery.noConflict()("#modalFeito").click(function(event){
        event.preventDefault();
        if ($("#fr-id").text()){
                //$("#form").submit();
                alert("estou aqui");
                $("#pesquisa-prod").modal('toggle');
            }
        else {  
            $("#form").submit();
        }
    });

    jQuery.noConflict()("#modal_teste").click(function(event){
        event.preventDefault();
            $("#email_modal_html").modal('toggle'); 
    });

    jQuery.noConflict()("#imprimir").click(function(event){
        event.preventDefault();
        if ($("#fr-id").text()){
                var fr_id = $("#fr-id").text();
                $.ajax({
                    type: "GET",
                    url: "{% url 'entradas:oc_print' %}",
                    data: {"id": fr_id},
                    success: function(response){
                        var w = window.open('about:blank');
                        w.document.open();
                        w.document.write(response);
                        w.document.close();
                    },
                    error: function(error){
                        alert(err.Message)
                    }
                })
            }
        else {  
            $("#form").submit();
        }
    });

    jQuery.noConflict()("#oc_pdf").click(function(event){
        var fr_id = $("#fr-id").text();
        $.ajax({
            type: "GET",
            url: "{% url 'entradas:oc_pdf' %}",
            data: {"id": fr_id},
            success: function(response){
                window.open("data:application/IMG," + escape(response));
            },
            error: function(error){
                alert(err.Message)
            }
        })
    });

   $("#email_modal").click(function(event){
        event.preventDefault();
        if ($("#fr-id").text()){
                var fr_id = $("#fr-id").text();
                $.ajax({
                    type: "GET",
                    url: "{% url 'entradas:oc_email' %}",
                    data: {"id": fr_id},
                    success: function(response){

                        $("#message").val(response);
                        $("#email_modal_html").modal('toggle'); 
                    },
                    error: function(error){
                        alert(err.Message)
                    }
                })
            }
        else {  
            $("#form").submit();
        }
    });

    $("#send_email").click(function(event){
        var fr_id = $("#fr-id").text();
        var message = $("#message").val();
        var to = $("#email_to").val();
        alert('auqi')
        $.ajax({
            type: "GET",
            url: "{% url 'entradas:send_email' %}",
            data: {"id": fr_id, "message": message, "to": email_to},
            success: function(response){
                alert('Email enviado');
                $("#email_modal_html").modal('toggle'); 
            },
            error: function(error){
                alert(err.Message)
            }
        })
    });

    jQuery.noConflict()("#pesquisar").click(function(event){
        var pesq = $("#pesquisa").val();
        $.ajax({
            type: "GET",
            url: "{% url 'entradas:nf_entrada_prod_search' %}",
            data: {"pesquisa": pesq},
            success: function(result){
                $("#prod-tab").html(result) 
            },
            error: function(error){
                alert(error)
            }

        })
    });

    jQuery.noConflict()("#prod-tab").on("click", ".btnSelect", function(event){
        event.preventDefault();
        var currentRow = $(this).closest("tr"); 
        var prod = currentRow.find("td:eq(0)").text();
        var fr_id = $("#fr-id").text();
        $.ajax({
            type: "POST",
            url: "{% url 'entradas:oc_item_add' %}",
            data: {"produto": prod, "id": fr_id, csrfmiddlewaretoken: '{{ csrf_token }}'},
            success: function(result){
                location.reload();
                $("#pesquisa-prod").modal('toggle'); 
            },
            error: function(error){
                alert('Não foi possível inserir o produto')
            }
        });
    });

    jQuery.noConflict()("#itens-table").on("click", ".delete-item", function(event){
        event.preventDefault();
        var currentRow = $(this).closest("tr"); 
        var item_id = currentRow.find("td:eq(0) input").val();
        $.ajax({
            type: "POST",
            url: "{% url 'entradas:oc_item_delete' %}",
            data: {"item_id": item_id, csrfmiddlewaretoken: '{{ csrf_token }}'},
            success: function(result){
                location.reload();
            },
            error: function(error){
                alert("Não foi possivel completar o processo")
            }
        });
    }); 

    jQuery.noConflict()("#delete").click(function(event){
        var fr_id = $("#fr-id").text();
        $.ajax({
            type: "POST",
            url: "{% url 'entradas:oc_delete' %}",
            data: {"id": fr_id, csrfmiddlewaretoken: '{{ csrf_token }}'},
            success: function(result){
                alert("OC Excluída com sucesso")
            },
            error: function(error){
                alert("A OC não pode ser excluído")
            }
        })
    })


})($)
</script>

{% endblock extrascripts %}

entradas/templates/entradas/oc_list_table.html
<table id="list-table" class="table">
    <thead>
    <tr>
      <th class="text-center" scope="col">#</th>
      <th class="text-center" scope="col">Número</th>
      <th class="text-center" scope="col">Data de Emissão</th>
      <th class="text-center" scope="col">Status</th>
      <th class="text-center" scope="col">Operacao</th>
      <th class="text-center" scope="col">Fornecedor</th>
      <th class="text-center" scope="col">Valor da nota</th>
      <th class="text-center" scope="col">Obs</th>
      <th class="text-center" scope="col">Read / Update / Delete</th>
    </tr>
    </thead>
    <tbody>
    {% for it in lista %}
      <tr>
        <th class="text-center" scope="row">{{ forloop.counter }}</th>
        <td class="text-center">{{ it.num }}</td>
        <td class="text-center">{{ it.data_emissao|date:"SHORT_DATE_FORMAT"}}</td>
        <td class="text-center">{{ it.status }}</td>
        <td class="text-center">{{ it.operacao }}</td>
        <td class="text-center">{{ it.parceiro }}</td>
        <td class="text-center">{{ it.valor_total_nota }}</td>
        <td class="clamp">{{ it.obs }}</td>
        <td class="text-center">
          <!-- Read book buttons -->
          <button type="button" class="read btn btn-sm btn-primary" data-form-url="{% url 'entradas:nf_entrada_read' it.pk %}">
            <span class="fa fa-eye"></span>
          </button>
          <!-- open pedido full -->
          <button type="button" id='detail' class="detail btn btn-sm btn-primary" data-form-url="{% url 'entradas:oc_detail' it.pk %}" >
            <span class="fa fa-pencil"></span>
          </button>
        </td>
      </tr>
    {% endfor %}
  
    </tbody>
  </table>